### ISSUE TITLE
Annotation failed in command line mode

### ISSUE THREAD

**Issue by JunYang2021** [phenomecentre/peakPantheR#35]
Hi, I have some .mzML LC-MS raw data files and a target feature list. I want to extract these features with peakPantheR. I have successfully extracted many features in GUI and visulaized the results. However, these same files can't be annotated in command line mode. The final error information is: 
```
----------------
3 file(s) failed to process:
                                     file                                 error
1   E:/mice/metab_pos_mzML/QC1_1_pos.mzML missing value where TRUE/FALSE needed
2 E:/mice/metab_pos_mzML/QC1_15V_pos.mzML missing value where TRUE/FALSE needed
3   E:/mice/metab_pos_mzML/QC1_2_pos.mzML missing value where TRUE/FALSE needed
No file left in the object!
Annotation object reordered by sample acquisition date
----------------
Parallel annotation done in: 2.18 mins
  3 failure(s)
```
Also, when processing, the suggestion in console is like:
```
----- QC1_2_pos -----
Acquisition date parsed in: 0 secs
Reading data from 164 windows
No data exist for window 2
No data exist for window 3
No data exist for window 5
No data exist for window 6
No data exist for window 9
No data exist for window 10
```
My processing code is:
```
path<- "E:/metab_pos_mzML"
files<-paste(path,list.files(path,recursive = TRUE),sep='/')
input_targetFeatTable<-read_csv('D:/metabolomics_pos.csv')
QC_files<-c(files[13:15])
init_annotation <- peakPantheRAnnotation(spectraPaths = QC_files,
                                         targetFeatTable = input_targetFeatTable)
annotation_result <- peakPantheR_parallelAnnotation(init_annotation, ncores=0,
                                                    curveModel='skewedGaussian',
                                                    verbose=TRUE)
```
I can ensure the cpdID column in .csv file is of character type. So how to process my data in command line mode? Hope to get your help!

**Comment by Gscorreia89** [comment]
Hi,

Thanks for your interest in peakPantheR. With a cursory glance at the code everything seems fine, so I would need some example data to replicate the problem - Would you be able to send me your 'metabolomics_pos.csv' file and 2 of your .mzML files so I can debug? If so, my email for data sharing gd2212_at_ic.ac.uk.

**Comment by JunYang2021** [comment]
Thank you for your reply. I have sent my data to your email. @Gscorreia89

**Comment by Gscorreia89** [comment]
Hi,

Thank you - just tried your data and could replicate (and pinpoint!) the error. It is caused by passing a tible instead of a data frame with the reference compounds. Typecasting it to a regular R data frame seems to have worked:

init_annotation <- peakPantheRAnnotation(spectraPaths = QC_files,
                                         targetFeatTable = data.frame(input_targetFeatTable))

Please let me know if this fixes it for you. We will add some checks in the command line version to ensure coherence with the GUI.

Thanks

**Comment by JunYang2021** [comment]
It worked. And I can successfully extracted the peaks. Thanks for your solution and this excellent tool.
