### ISSUE TITLE
Hello, installed the package and get these errors when I am inporting data

### ISSUE THREAD

**Issue by xulei99** [phenomecentre/peakPantheR#37]
Warning in bslib::page_navbar(..., title = title, id = id, selected = selected,  :
  Unable to infer a `window_title` default from `title`. Consider providing a character string to `window_title`.
Warning: Error in cpdID: could not find function "cpdID"
  2: shiny::runApp
  1: peakPantheR::peakPantheR_start_GUI
Warning: Error in <Anonymous>: unable to find an inherited method for function ‘isAnnotated’ for signature ‘"logical"’
  118: stop
  117: <Anonymous>
  116: peakPantheR::isAnnotated
  115: <reactive:runSuccess> [server/server_run.R#161]
   99: runSuccess
   98: renderText [server/server_run.R#195]
   97: func
   84: renderFunc
   83: output$AnnotationDone
    2: shiny::runApp
    1: peakPantheR::peakPantheR_start_GUI
[1] "could not find function \"spectraPaths_and_metadata_UI_helper\""

**Comment by adwolfer** [comment]
Hello, thank you for the report, could I ask which version of `R` and `peakPantheR` you ran?
I tried to reproduce the same situation on a fresh install with `R 4.2.2` and `peakPantheR 1.12.2` (the current Bioconductor version), but cannot trigger the error message relating to `bslib`

**Comment by xulei99** [comment]
Hello, I tried the R4.1.3 and peakPantheR 1.8.0 on Windows 11, and got that error. While I just tried R4.1.3 and peakPantheR 1.12.2 on Ubuntu ​ 20.04, it is working now.

**Comment by adwolfer** [comment]
This seems correct, the bslib issue was addressed in February 2022 as far as I can see. I’m not certain of the Bioconductor rules regarding minimum R versions for each release, but would expect that peakPantheR 1.2.2 on windows would also solve the issue.
